version: '3'
services:
  myapp:
    image: myapp:1.0
    container_name: myapp
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - mynetwork
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - mynetwork  # Specify the custom network
    volume:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=test
      - ME_CONFIG_BASICAUTH_PASSWORD=test
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
     - mongodb
    networks:
      - mynetwork  # Specify the custom network

networks:
  mynetwork:  # Define the custom network
    driver: bridge  # The default bridge driver
